### ISSUE TITLE
Possible support for FontAwesome 6

### ISSUE THREAD

**Issue by Aetherinox** [gapmiss/badges#6]
I'm not sure what needs implemented, but I was wondering how much work it would be to offer one of two solutions:
1. A way to add custom icons using maybe the SVG path, and being able to also define the text label, and a custom color.
2. Support for FontAwesome 6 icons using the font-awesome names.

Either one would work, but I'd imagine doing Option 1 would be much easier. Just having a settings panel for the plugin which allows you to simply copy/paste an SVG path and it showing that icon on the label.

There are other plugins like Iconize which support icon packages, but it makes you import all .svg icon files and the plugin stores them in a folder, and then the icons appear in a context menu to pick from. And that may be a lot of work, compared to just a simple SVG path.

**Comment by gapmiss** [comment]
Thanks for the detailed suggestion. Unfortunately this is outside what I want to take on for the plugin. FontAwesome brings licensing and bundling complexity, and a custom SVG settings panel adds a fair amount of UI/storage work for what's ultimately an edge case.

If you need a specific icon, one workaround is using the customized badge type and overriding the icon via CSS in a snippet.

###### Example

**Badge:**
```
`[!!customized:My Custom Badge]`
```

**CSS snippet:**
```css
.inline-badge[data-inline-badge="customized"] .inline-badge-icon {
 position: relative;
 display: inline-flex;
 width: 16px;
 height: 16px;
}

.inline-badge[data-inline-badge="customized"] .inline-badge-icon svg {
 display: none;
}

.inline-badge[data-inline-badge="customized"] .inline-badge-icon::before {
 content: "";
 position: absolute;
 top: 0;
 left: 0;
 width: 16px;
 height: 16px;
 background-color: currentColor;
 -webkit-mask-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='...'/></svg>");
 mask-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='...'/></svg>");
 -webkit-mask-size: contain;
 mask-size: contain;
}
```
Note: use filled SVGs (not stroked) for best results.
